baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Beatriz Severes.io'
theme = 'hugo-theme-relearn'

    
[params]
  themeVariant = "my-variant"
  menuPre = 'kkkk ' 
  Pre = '@'
  disableSearch = true
  disableLandingPageButton = true